<!-- 活动列表 -->
<script type="text/x-jsrender" id="campListTmp">
	<img src="http://dl.bizhi.sogou.com/images/2012/03/14/124196.jpg">
	<span class="campDetail">
		<span class="title">{{:title}}</span>
		<span class="departure">{{:departure}}</span>
		<span class="starTime">{{:starTime}}</span>	
		<span class="price">¥{{:price}}</span>
	</span>
</script>
<!-- 活动详情 -->
<script type="text/x-jsrender" id="detailTmp">
	<li class="detailList">
		<p class="camp_title">{{:campTitle}}</p>
    	<div class="camp_content">{{:campContent}}</div>
	</li>
</script>